### ISSUE TITLE
Implement resource cache with constant seek time

### ISSUE THREAD

**Issue by luigizhou** [ish-xyz/kube-shield#2]
-----
```
clusterPolicies:
   group:
     version:
       resource:
         rules:
         - x
         - y
         - z 
 ```
----
```
$NSNAME:
   group:
     version:
       resource:
         rules:
         - x
         - y
         - z
   ```
